title: 你的博客标题
description: 这是我的个人博客
baseurl: ""  # 如果是用户名.github.io，这里保持空字符串
url: "https://你的用户名.github.io"  # 替换为你的地址

theme: minima

# 让Jekyll包含自定义的_layouts和assets.css
include:
  - _layouts
  - assets.css
